#  func_schema_setup() {
#    if [ "$schema_setup" == "mongo" ]; then
#    func_print_head "Copy MongoDB repo"
#    cp ${script_path}/mongo.repo /etc/yum.repos.d/mongo.repo &>>$log_file
#    func_stat_check $?

#    func_print_head "Install MongoDB Client"
#    yum install mongodb-org-shell -y &>>$log_file
#    func_stat_check $?

#    func_print_head "Load Schema"
#    mongo --host mongodb-dev.ndevopsb72.online </app/schema/${component}.js &>>$log_file
#    func_stat_check $?
#    fi
#    if [ "${schema_setup}" == "mysql" ]; then
#    func_print_head "Install MySQL Client"
#    yum install mysql -y &>>$log_file
#    func_stat_check $?

#    func_print_head "Load Schema"
#    mysql -h mysql-dev.ndevopsb72.online -uroot -p${mysql_root_password} < /app/schema/shipping.sql &>>$log_file
#    func_stat_check $?
#    fi
#  }
- name: Load mongodb schema
  when: schema_setup == "mongodb"
  block:
    - name: copy mongodb repo file
      ansible.builtin.copy:
        src: mongo.repo
        dest: /etc/yum.repos.d/mongo.repo
      

    - name: Install Mongodb client
      ansible.builtin.yum:
        name: mongodb-org-shell
        state: installed
      

    - name: Load Schema
      ansible.builtin.shell: mongo --host {{ lookup('aws_ssm', 'dev.catalogue.mongo_endpoint', region='us-east-1' ) }} </app/schema/{{component}}.js



- name: Load mysql schema
  when: schema_setup == "mysql"
  block:
    - name: Install mysql
      ansible.builtin.yum:
        name: mysql

    - name: Load schema
      ansible.builtin.shell: mysql-h{{ lookup('aws_ssm', 'dev.shipping.db_host', region='us-east-1' ) }} -u{{ lookup('aws_ssm', 'dev.shipping.db_user', region='us-east-1' ) }} -p{{ lookup('aws_ssm', 'dev.shipping.db_pass', region='us-east-1' ) }} </app/schema/{{component}}.sql




